version: "3"

services:
  web:
    image: ussd-service 
    depends_on:
      - mariadb
    ports:
      - '8080:8080'
    links:
      - mariadb
  mariadb:
    image: "mariadb"
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ussd